apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: travels
  description: An example of a Kiali demo travels application.
  tags:
    - istio
    - kiali
    - travels
    - servicemesh
  annotations:
    "backstage.io/kubernetes-id": travels
spec:
  type: service
  lifecycle: production
  owner: user:guest
